export const REQUEST_CONTENT_LIST = 'REQUEST_CONTENT_LIST'
export const GET_CONTENT_LIST = 'GET_CONTENT_LIST'
export const ADD_CONTENT_LIST = 'ADD_CONTENT_LIST'
export const GET_CONTENT_LIST_FAILURE = 'GET_CONTENT_LIST_FAILURE'

export const REQUEST_PROJECT_COLUMN_LIST = 'REQUEST_PROJECT_COLUMN_LIST'
export const GET_PROJECT_COLUMN_LIST = 'GET_PROJECT_COLUMN_LIST'
export const GET_PROJECT_COLUMN_LIST_FAILURE = 'GET_PROJECT_COLUMN_LIST_FAILURE'

export const REQUEST_PROJECT_TRIP_LIST = 'REQUEST_PROJECT_TRIP_LIST'
export const GET_PROJECT_TRIP_LIST = 'GET_PROJECT_TRIP_LIST'
export const GET_PROJECT_TRIP_LIST_FAILURE = 'GET_PROJECT_TRIP_LIST_FAILURE'

export const REQUEST_PROJECT_INTERACT_LIST = 'REQUEST_PROJECT_INTERACT_LIST'
export const GET_PROJECT_INTERACT_LIST = 'GET_PROJECT_INTERACT_LIST'
export const GET_PROJECT_INTERACT_LIST_FAILURE = 'GET_PROJECT_INTERACT_LIST_FAILURE'

export const REQUEST_COMMENT_LIST = 'REQUEST_COMMENT_LIST'
export const GET_COMMENT_LIST = 'GET_COMMENT_LIST'
export const ADD_COMMENT_LIST = 'ADD_COMMENT_LIST'
export const GET_COMMENT_LIST_FAILURE = 'GET_COMMENT_LIST_FAILURE'

export const REQUEST_LIKE = 'REQUEST_LIKE'
export const REMOVE_LIKE = 'REMOVE_LIKE'
export const ADD_LIKE = 'ADD_LIKE'
export const GET_LIKE_FAILURE = 'GET_LIKE_FAILURE'

export const REQUEST_COMMENT = 'REQUEST_COMMENT'
export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'
