export const REQUEST_PROJECT_LIST = 'REQUEST_PROJECT_LIST'
export const GET_PROJECT_LIST = 'GET_PROJECT_LIST'
export const ADD_PROJECT_LIST = 'ADD_PROJECT_LIST'
export const GET_PROJECT_LIST_FAILURE = 'GET_PROJECT_LIST_FAILURE'

export const REQUEST_HOME_PROJECT_LIST = 'REQUEST_HOME_PROJECT_LIST'
export const GET_HOME_PROJECT_LIST = 'GET_HOME_PROJECT_LIST'
export const ADD_HOME_PROJECT_LIST = 'ADD_HOME_PROJECT_LIST'
export const GET_HOME_PROJECT_LIST_FAILURE = 'GET_HOME_PROJECT_LIST_FAILURE'

export const REQUEST_PROJECT_COLUMN_LIST = 'REQUEST_PROJECT_COLUMN_LIST'
export const GET_PROJECT_COLUMN_LIST = 'GET_PROJECT_COLUMN_LIST'
export const GET_PROJECT_COLUMN_LIST_FAILURE = 'GET_PROJECT_COLUMN_LIST_FAILURE'

export const REQUEST_COMMENT_LIST = 'REQUEST_COMMENT_LIST'
export const GET_COMMENT_LIST = 'GET_COMMENT_LIST'
export const ADD_COMMENT_LIST = 'ADD_COMMENT_LIST'
export const GET_COMMENT_LIST_FAILURE = 'GET_COMMENT_LIST_FAILURE'

export const REQUEST_LIKE = 'REQUEST_LIKE'
export const REMOVE_LIKE = 'REMOVE_LIKE'
export const ADD_LIKE = 'ADD_LIKE'
export const GET_LIKE_FAILURE = 'GET_LIKE_FAILURE'

export const REQUEST_COMMENT = 'REQUEST_COMMENT'
export const ADD_COMMENT = 'ADD_COMMENT'
export const ADD_COMMENT_FAILURE = 'ADD_COMMENT_FAILURE'

export const REQUEST_GET_USERINFO = 'REQUEST_GET_USERINFO'
export const GET_USERINFO = 'GET_USERINFO'
export const GET_USERINFO_FAILURE = 'GET_USERINFO_FAILURE'

export const REQUEST_SET_USERINFO = 'REQUEST_SET_USERINFO'
export const SET_USERINFO = 'SET_USERINFO'
export const SET_USERINFO_FAILURE = 'SET_USERINFO_FAILURE'

export const REQUEST_PROJECT_DETAILS = 'REQUEST_PROJECT_DETAILS'
export const GET_PROJECT_DETAILS = 'GET_PROJECT_DETAILS'
export const GET_PROJECT_DETAILS_FAILURE = 'GET_PROJECT_DETAILS_FAILURE'

export const REQUEST_ORDER_LIST = 'REQUEST_ORDER_LIST'
export const GET_ORDER_LIST = 'GET_ORDER_LIST'
export const ADD_ORDER_LIST = 'ADD_ORDER_LIST'
export const GET_ORDER_LIST_FAILURE = 'GET_ORDER_LIST_FAILURE'

export const REQUEST_CANCEL_ORDER = 'REQUEST_CANCEL_ORDER'
export const CANCEL_ORDER = 'CANCEL_ORDER'
export const CANCEL_ORDER_FAILURE = 'CANCEL_ORDER_FAILURE'

export const REQUEST_CAPTCHA = 'REQUEST_CAPTCHA'
export const GET_CAPTCHA = 'GET_CAPTCHA'
export const GET_CAPTCHA_FAILURE = 'GET_CAPTCHA_FAILURE'
export const REQUEST_CHECK_CAPTCHA = 'REQUEST_CHECK_CAPTCHA'
export const CHECK_CAPTCHA = 'CHECK_CAPTCHA'
export const CHECK_CAPTCHA_FAILURE = 'CHECK_CAPTCHA_FAILURE'

export const SET_TOKEN = 'SET_TOKEN'
export const SET_USER = 'SET_USER'
export const LOADING = 'LOADING'

export const SHOW_MSG = 'SHOW_MSG'
export const HIDE_MSG = 'HIDE_MSG'
