export const REQUEST_CONTENT_LIST = 'REQUEST_CONTENT_LIST'
export const GET_CONTENT_LIST = 'GET_CONTENT_LIST'
export const GET_CONTENT_LIST_FAILURE = 'GET_CONTENT_LIST_FAILURE'

export const REQUEST_PROJECT_COLUMN_LIST = 'REQUEST_PROJECT_COLUMN_LIST'
export const GET_PROJECT_COLUMN_LIST = 'GET_PROJECT_COLUMN_LIST'
export const GET_PROJECT_COLUMN_LIST_FAILURE = 'GET_PROJECT_COLUMN_LIST_FAILURE'
